### PR TITLE
Allow build of main library and tests using CMake rather than QMake

### PR DESCRIPTION
**Pull request by arcadien**
For instance, the patch allow : 
- Configuration and compilation of main library
- Compilation of tests and examples
- Creation of the CMake configuration file

### CODE REVIEW

**Comment by VSRonin** [comment]
Looks good to me.
The only minor detail is that you enabled BUILD_EXAMPLES but not made a CMakeLists.txt for the examples.
I'm not a CMake expert so I'll leave this open for a few days to allow other people to review and then merge

**Comment by arcadien** [comment]
Hello,

no problem. In the meantime i will have a look if i can finish the 
implementation for examples too, or remove it.

Regards,

**Comment by arcadien** [comment]
Examples are now built but not installed

**Comment by arcadien** [comment]
There is a bug : include files are "make installed" at configuration step rather than installation step

**Comment by VSRonin** [comment]
Also, DEBUG_POSTFIX "d" applies to windows only, on mac it's "_debug" and nothing on linux

**Comment by arcadien** [comment]
Fixed

**Comment by VSRonin** [comment]
Will merge this tomorrow if nothing else is still pending

**Comment by arcadien** [comment]
I still have problems with "include files are "make installed" at configuration step rather than installation step"

**Comment by arcadien** [comment]
I did not reproduced the problem. Did you try to build with cmake?

**Comment by VSRonin** [comment]
I did and never noticed the "make installed at configuration". I even did it twice just to check when includes were created, that's why I wanted to merge, I thought it was solved

**Comment by Guigo-** [comment]
I build release and debug with MinGW, everything is fine and I didn't notice any error about include files. There are some news about merging this pull request ?

**Comment by arcadien** [comment]
Issue with includes was fixed when adding compatibility with Linux/GCC build. I created another pull request so you can decline/delete this one. Sorry for the delay.

**Pull request closed without merging**
